vim.cmd('syntax on')
vim.cmd('set relativenumber')
vim.cmd('set tabstop=2 softtabstop=2')
vim.cmd('set shiftwidth=4')
vim.cmd('set expandtab')
vim.cmd('set smartindent')
vim.cmd('set hls ic')
vim.cmd('set so=8')
vim.cmd('set showcmd')
vim.cmd('set cursorline')
vim.cmd('set nocompatible')
vim.cmd('set termguicolors')
vim.cmd('let ayucolor="dark"')
vim.cmd('colorscheme ayu')
